apiVersion: apps/v1
kind: Deployment
metadata:
  name: kline-analytics
  labels:
    app: kline-analytics
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kline-analytics
  template:
    metadata:
      labels:
        app: kline-analytics
    spec:
      containers:
      - name: kline-analytics
        image: kline-analytics:local
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: JAVA_OPTS
          value: "-Xms256m -Xmx512m"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector:4318"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 12
---
apiVersion: v1
kind: Service
metadata:
  name: kline-analytics-service
  labels:
    app: kline-analytics
spec:
  selector:
    app: kline-analytics
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: kline-analytics-headless
  labels:
    app: kline-analytics
spec:
  selector:
    app: kline-analytics
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  clusterIP: None
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kline-analytics-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: kline-analytics
