server:
  port: 8080
spring:
  application:
    name: kline-analytics
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB
logging:
  level:
    root: INFO
    com.stocksanalyses: INFO
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
ocr:
  enabled: true
  tessdataPath: 
  language: eng

