server:
  port: 8080
spring:
  application:
    name: kline-analytics
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB
  datasource:
    timescale:
      url: ${TIMESCALE_URL:jdbc:postgresql://localhost:5432/market}
      driver-class-name: org.postgresql.Driver
      username: ${TIMESCALE_USER:postgres}
      password: ${TIMESCALE_PASS:postgres}
    clickhouse:
      url: ${CLICKHOUSE_URL:jdbc:clickhouse://localhost:8123/market}
      driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
      username: ${CLICKHOUSE_USER:default}
      password: ${CLICKHOUSE_PASS:}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        envers:
          audit_table_suffix: _aud
          store_data_at_delete: true
logging:
  level:
    root: INFO
    com.stocksanalyses: INFO
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
        http.client.requests: true
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99
        http.client.requests: 0.5, 0.95, 0.99
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
ocr:
  enabled: true
  tessdataPath: 
  language: eng
# JWT Configuration
jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400000 # 24 hours
# Rate Limiting Configuration
rate-limit:
  default-requests-per-minute: 100
  default-requests-per-hour: 1000
# Privacy Configuration
privacy:
  anonymize-data: false
  persist-images: true
  data-retention-days: 30
# Segmentation Configuration
seg:
  endpoint: http://localhost:8088/predict
  timeoutMs: 4000
  enabled: true
  forceSegmentation: false  # if true, skip geometry fallback
  forceGeometry: false      # if true, skip segmentation
  # Model-specific settings
  model:
    type: yolov8-seg  # yolov8-seg, mask-rcnn, sam2
    confidenceThreshold: 0.5
    nmsThreshold: 0.4
    maxInstances: 100
  # Fusion parameters
  fusion:
    pixelsPerBar: 6.0
    maxCandles: 50
    wickProximityFactor: 0.6  # multiplier for pixelsPerBar to find nearby wicks
    minCandleHeight: 3.0      # minimum pixel height for valid candle
    minWickLength: 2.0        # minimum pixel length for valid wick
  # Class mapping (adjust based on your model's output classes)
  classes:
    candle: ["candle", "body", "candlestick"]
    wick: ["wick", "shadow", "line"]
  # Quality thresholds
  quality:
    minScore: 0.3             # minimum confidence score for instances
    minPolygonPoints: 4       # minimum points in mask polygon
    maxPolygonPoints: 1000    # maximum points in mask polygon

# Market Data Configuration
marketdata:
  primary-provider: timescale  # timescale, clickhouse
  reconciliation:
    enabled: true
    tolerance: 0.01  # Price difference tolerance for reconciliation
  timescale:
    table: candles
  clickhouse:
    table: candles
  corporate-actions:
    table: corporate_actions

