# Canary environment values
replicaCount: 1

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

java:
  heap:
    initial: "512m"
    maximum: "1g"

env:
  - name: SPRING_PROFILES_ACTIVE
    value: "canary"
  - name: JAVA_OPTS
    value: "-Xms512m -Xmx1g -XX:+UseG1GC -Dspring.profiles.active=canary"
  - name: LOGGING_LEVEL_ROOT
    value: "INFO"
  - name: CANARY_TRAFFIC_PERCENTAGE
    value: "10"

healthChecks:
  liveness:
    initialDelaySeconds: 60
    periodSeconds: 30
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 10
  startup:
    initialDelaySeconds: 10
    periodSeconds: 5
    failureThreshold: 12

gracefulShutdown:
  terminationGracePeriodSeconds: 30

podAntiAffinity:
  enabled: false

monitoring:
  serviceMonitor:
    enabled: true
    interval: 30s
    labels:
      environment: canary
  prometheusRule:
    enabled: true

logging:
  level: INFO
  sampling:
    enabled: true
    rate: 0.1

backup:
  enabled: false

prometheus:
  enabled: true
  server:
    persistentVolume:
      enabled: true
      size: 20Gi

grafana:
  enabled: true
  adminPassword: "canary-admin"

elasticsearch:
  enabled: true
  replicas: 1
  persistence:
    enabled: true
    size: 20Gi

kibana:
  enabled: true
  replicas: 1

# Canary-specific configurations
canary:
  enabled: true
  trafficPercentage: 10
  metrics:
    - name: "error_rate"
      threshold: 0.05
    - name: "response_time_p99"
      threshold: 1000
    - name: "cpu_usage"
      threshold: 80
  rollback:
    enabled: true
    threshold: 3 # failures before rollback
